import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F6FA",
  },
  scrollContent: {
    paddingBottom: 25, // Aumentado para dar espaço ao footer fixo
  },
  topSection: {
    backgroundColor: "#8E7CFF",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileSummary: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatarWrapper: {
    width: 52,
    height: 52,
    borderRadius: 31,
    backgroundColor: "rgba(255,255,255,0.22)",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  profileText: {
    marginLeft: 14,
    justifyContent: "center",
    flexShrink: 1,
  },
  topIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  welcomeTextWrapper: {
    marginTop: 22,
  },
  welcomeText: {
    color: "#fff",
    fontSize: 16,
  },
  userName: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "700",
    marginTop: -5,
  },
  subtitle: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 15,
    marginTop: 10,
    lineHeight: 22,
    maxWidth: "85%",
  },
  searchContainer: {
    marginTop: 24,
    backgroundColor: "#A99EFF",
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchLabel: {
    marginLeft: 14,
    color: "#ffffff",
    fontSize: 15,
  },
  sectionHeader: {
    marginTop: 22,
    marginHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#161828",
  },
  quickActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    marginHorizontal: 24,
  },
  actionCard: {
    backgroundColor: "#fff",
    flex: 1,
    borderRadius: 18,
    padding: 16,
    marginRight: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  actionIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(106,55,229,0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  actionTitle: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: "700",
    color: "#161828",
  },
  actionSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: "#7A7A92",
  },
  promoCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    marginLeft: 25,
    marginRight: 33,
    marginTop: 18,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  promoText: {
    flex: 1,
    paddingRight: 12,
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F1F35",
    lineHeight: 22,
  },
  promoDescription: {
    fontSize: 13,
    color: "#7A7A92",
    marginTop: 10,
    lineHeight: 20,
  },
  promoButton: {
    marginTop: 16,
    backgroundColor: "#8E7CFF",
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
  },
  promoButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  promoIllustration: {
    width: 90,
    height: 90,
    borderRadius: 20,
    backgroundColor: "#8E7CFF",
    justifyContent: "center",
    alignItems: "center",
  },
  sessionCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    marginHorizontal: 24,
    marginTop: 18,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  sessionInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sessionDate: {
    fontSize: 14,
    color: "#7A7A92",
  },
  sessionTime: {
    fontSize: 18,
    fontWeight: "700",
    color: "#161828",
  },
  sessionButton: {
    marginTop: 18,
    backgroundColor: "#22C55E",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
  },
  sessionButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
});

export default styles;
